### ISSUE TITLE
Download link request

### ISSUE THREAD

**Issue by alex08211** [asamm/locus-addon-wearables#11]
Hi , Menion, can you provide more ways to download the latest apk file not only on google play store please ? since my watch doesn't have google play store , I really want the wear addon apk file , thank you.

**Comment by alex08211** [comment]
Solved, the locus team has sent me a link:https://drive.google.com/drive/mobile/folders/1U8U1D-NGQ9CAnqXAkleEXi46wH2T7tMR?usp=sharing

**Comment by menion** [comment]
Perfect.
