### ISSUE TITLE
Alternative download source

### ISSUE THREAD

**Issue by IzzySoft** [asamm/locus-addon-wearables#5]
Hi Menion, would you consider attaching the `.apk` file to the releases here, so folks without Playstore can grab it? I'd then offer to serve it via [my F-Droid compatible repo](https://apt.izzysoft.de/fdroid), including automated updates.

**Comment by milan-asamm** [comment]
Hello IzzySoft,
we will share APKs for Wear for Locus Map at this link https://nas.asamm.com/share.cgi?ssid=0k1ERCo
The first release version is already there.
Milan

**Comment by IzzySoft** [comment]
Thanks Milan – but unfortunately, my auto-updater cannot pick it from such an URL. It works with Github releases, or the APK inside an repo, or a "fixed link" (like `https://example.com/example.apk`) only. Apart from that, the URL you gave has SSL issues ("The certificate is not trusted because the issuer certificate is unknown." aka SEC_ERROR_UNKNOWN_ISSUER).

**Comment by milan-asamm** [comment]
Hello,
sorry about the certificate issue, we intend to fix this in the future.
We will continue to share APKs under this link and do not plan to release it via Github or put APKs inside the repository. The main distribution channel for this add-on is Google Play and it also requires Google Play Services to work anyway so I suppose number of people without Google Play will be minimal.

**Comment by IzzySoft** [comment]
There's always *microG* as replacement of the play services :wink:

But understood. It seems the LocusPro version without license check via `vending.CHECK_LICENSE` never "went public" either, which is a pity (as it works well with microG).

So will you update this issue when the certificate is fixed? Thanks in advance!

**Comment by milan-asamm** [comment]
Ok, no problem. I have created an internal issue for this to remind me to post here when we replace the self-signed certificate.

**Comment by IzzySoft** [comment]
@milan-asamm Just a "heads-up" reminder – joined with the question whether you then will provide a "fixed link" as described above?

**Comment by alex08211** [comment]
Hi, the link above is invalid,can you share the latest wear addon apk or download link please? Since my watch doesn't have google play store , I can't get it anywhere , thank you .

**Comment by menion** [comment]
I'll try not to forget and add the latest published Wear add-on versions to the shared public directory next to Locus Map/Locus Map Classic versions.

Link: http://bit.ly/lmVersions
